// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// ============================================================
//  Groth16Verifier
//  Auto-generated by snarkJS from AgeVerify.circom
//  DO NOT edit the constants below.
// ============================================================
contract Groth16Verifier {
    uint256 constant r  = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 constant q  = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    uint256 constant alphax  = 6292748866740156383278934603562899437220855671083194355178909688307445812321;
    uint256 constant alphay  = 8804407489043322461571050883940134586097931688946528538916332296741494692705;
    uint256 constant betax1  = 2239029851410950618641036847306782331497542193157841364453609130969623670077;
    uint256 constant betax2  = 21830893302736794455333098750668191178150038279217179074090418223198778140955;
    uint256 constant betay1  = 4364786949037099392876506437102540182967310020236621773991659526363029472708;
    uint256 constant betay2  = 20608725078074919373295390840268892754546145509792486468523241473096128595019;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 6622959211502676647784587953122441334073134387818955457423135422036084742075;
    uint256 constant deltax2 = 21208540251571310434400226073364151287273806488049499725762809707768022888436;
    uint256 constant deltay1 = 5392385877429135044204659743498648018810165462447749768886653402729006995913;
    uint256 constant deltay2 = 15626890980993724869862927284887767128177502190935449889160097378344362265829;

    uint256 constant IC0x = 16703044355869882497318946388490646579061635673897198303140421745374763859169;
    uint256 constant IC0y = 17362006844619018602919246650311970138567893717204991332867360442912633720952;
    uint256 constant IC1x = 19372493620812123148772325725753177963720995072112384102327831386494452194507;
    uint256 constant IC1y = 11939748112727652495990848262546933501671572296183904444329747588530061967147;
    uint256 constant IC2x = 19425933925487457264021332469739539823267296906640082660621666948682055839919;
    uint256 constant IC2y = 18441195435933036450990880065281841834723566862264629533166102463425132825018;
    uint256 constant IC3x = 1721870637114523580966255576555334712153627491828894256509030028312098963068;
    uint256 constant IC3y = 17281947395275593072097438878966619066977029751081716724616360387521446364727;
    uint256 constant IC4x = 18588338762356468428061141470206971841356385921854524202369989004252158983218;
    uint256 constant IC4y = 21147854589579066795098578917126318833709340365208506318583297016496947194289;
    uint256 constant IC5x = 15133486494673614141977968355622323069499005043614857014395992864551661116194;
    uint256 constant IC5y = 18914495807246262683839163754541622236827044405789092622117199879357808763361;

    uint16 constant pVk      = 0;
    uint16 constant pPairing = 128;
    uint16 constant pLastMem = 896;

    function verifyProof(
        uint[2]    calldata _pA,
        uint[2][2] calldata _pB,
        uint[2]    calldata _pC,
        uint[5]    calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)
                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) { mstore(0, 0) return(0, 0x20) }
                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))
                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) { mstore(0, 0) return(0, 0x20) }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk      := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))

                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))
                mstore(add(_pPairing, 64),  calldataload(pB))
                mstore(add(_pPairing, 96),  calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)
                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))
            checkField(calldataload(add(_pubSignals, 96)))
            checkField(calldataload(add(_pubSignals, 128)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)
            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}

// ============================================================
//  AgeVerifier
//  Deploy THIS contract only — it creates Groth16Verifier
//  internally. No constructor arguments needed.
// ============================================================
contract AgeVerifyExtension {

    Groth16Verifier public immutable verifier;

    mapping(address => bool)    public isAdultVerified;
    mapping(address => uint256) public verifiedAt;

    event AgeVerified(address indexed user, uint256 timestamp);

    /// @dev Deploys and owns its own Groth16Verifier instance.
    constructor() {
        verifier = new Groth16Verifier();
    }

    /**
     * @dev Submit a ZK proof to verify age >= 18.
     * @param a      Groth16 proof A  [2]
     * @param b      Groth16 proof B  [2][2]
     * @param c      Groth16 proof C  [2]
     * @param input  Public signals: [isAdult=1, currentYear, currentMonth, currentDay, minAge=18]
     */
    function submitAgeProof(
        uint[2]    calldata a,
        uint[2][2] calldata b,
        uint[2]    calldata c,
        uint[5]    calldata input
    ) external {
        require(input[0] == 1,  "Proof: isAdult must be 1");
        require(input[4] == 18, "Proof: minAge must be 18");
        require(input[1] >= 2020 && input[1] <= 2100, "Proof: invalid currentYear");
        require(input[2] >= 1 && input[2] <= 12,      "Proof: invalid currentMonth");
        require(input[3] >= 1 && input[3] <= 31,      "Proof: invalid currentDay");

        require(verifier.verifyProof(a, b, c, input), "Invalid ZK proof");

        isAdultVerified[msg.sender] = true;
        verifiedAt[msg.sender]      = block.timestamp;

        emit AgeVerified(msg.sender, block.timestamp);
    }

    function checkAdultStatus(address user) external view returns (bool) {
        return isAdultVerified[user];
    }

    function getVerificationDetails(address user)
        external view
        returns (bool verified, uint256 timestamp)
    {
        return (isAdultVerified[user], verifiedAt[user]);
    }
}
